import {StyleSheet} from 'react-native';
import {Colors} from '../../constants/colors';
import {FontSize, FontWeight} from '../../constants/fonts';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: Colors.background},
  scroll: {flex: 1},

  // ── Earnings Hero Card (standalone green, Blinkit style) ──
  earningsHero: {
    backgroundColor: Colors.primary,
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 24,
    padding: 22,
    shadowColor: Colors.shadow,
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.22,
    shadowRadius: 16,
    elevation: 8,
  },
  earningsHeroLabel: {
    fontSize: FontSize.xs,
    color: 'rgba(255,255,255,0.6)',
    fontWeight: FontWeight.medium,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
  },
  earningsHeroRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  earningsHeroAmount: {
    fontSize: FontSize.display,
    fontWeight: FontWeight.extraBold,
    color: Colors.text.inverse,
    letterSpacing: -0.5,
  },
  earningsHeroRight: {alignItems: 'flex-end', justifyContent: 'flex-end'},
  earningsHeroDeliveries: {
    fontSize: FontSize.base,
    color: Colors.cta,
    fontWeight: FontWeight.bold,
    marginBottom: 4,
  },
  earningsHeroTier: {
    fontSize: FontSize.xs,
    color: 'rgba(255,255,255,0.55)',
  },

  // ── Online / Offline Button (big, full-width, Blinkit style) ──
  onlineBtnWrap: {
    paddingHorizontal: 16,
    marginTop: 14,
    marginBottom: 4,
  },
  onlineBtnOffline: {
    backgroundColor: Colors.primary,
    borderRadius: 18,
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
    shadowColor: Colors.primaryDark,
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 6,
  },
  onlineBtnOnline: {
    backgroundColor: Colors.ctaLight,
    borderRadius: 18,
    paddingVertical: 18,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
    borderWidth: 1.5,
    borderColor: Colors.accent,
  },
  onlineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Colors.online,
  },
  onlineBtnTextOffline: {
    color: Colors.text.inverse,
    fontWeight: FontWeight.extraBold,
    fontSize: FontSize.md,
    letterSpacing: 0.5,
  },
  onlineBtnTextOnline: {
    color: Colors.primaryDark,
    fontWeight: FontWeight.extraBold,
    fontSize: FontSize.md,
    letterSpacing: 0.3,
  },

  // ── Stats ─────────────────────────────────────────────
  statsSection: {paddingHorizontal: 16, marginTop: 20},
  statsTitle: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
    color: Colors.text.secondary,
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  statsRow: {flexDirection: 'row', gap: 10},
  statCard: {
    flex: 1,
    backgroundColor: Colors.card,
    borderRadius: 16,
    padding: 14,
    alignItems: 'center',
    shadowColor: Colors.shadow,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 3,
  },
  statIconBg: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  statEmoji: {fontSize: 20},
  statValue: {
    fontSize: FontSize.lg,
    fontWeight: FontWeight.extraBold,
    color: Colors.text.primary,
  },
  statLabel: {
    fontSize: FontSize.xs,
    color: Colors.text.secondary,
    textAlign: 'center',
    marginTop: 2,
  },

  // ── Active Order ───────────────────────────────────────
  activeSection: {paddingHorizontal: 16, marginTop: 20},
  sectionTitle: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
    color: Colors.text.secondary,
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  activeCard: {
    backgroundColor: Colors.card,
    borderRadius: 20,
    padding: 18,
    shadowColor: Colors.shadow,
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
    borderWidth: 1,
    borderColor: Colors.borderLight,
  },
  activePulse: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 14,
  },
  activeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.online,
  },
  activePulseText: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
    color: Colors.online,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    flex: 1,
  },
  distancePill: {
    backgroundColor: Colors.primary + '12',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  distanceText: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
    color: Colors.primary,
  },
  activeCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  orderTypeTag: {
    backgroundColor: Colors.primary + '15',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
  },
  orderTypeText: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
    color: Colors.primary,
  },
  customerRow: {flexDirection: 'row', alignItems: 'center', marginBottom: 6, gap: 8},
  customerIcon: {fontSize: 16},
  customerName: {
    fontSize: FontSize.base,
    fontWeight: FontWeight.bold,
    color: Colors.text.primary,
  },
  customerAddress: {
    fontSize: FontSize.sm,
    color: Colors.text.secondary,
    marginLeft: 24,
    marginBottom: 14,
    lineHeight: 18,
  },
  viewOrderBtn: {
    backgroundColor: Colors.primary,
    borderRadius: 12,
    paddingVertical: 13,
    alignItems: 'center',
    shadowColor: Colors.shadow,
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 4,
  },
  viewOrderText: {
    color: Colors.text.inverse,
    fontWeight: FontWeight.bold,
    fontSize: FontSize.base,
    letterSpacing: 0.3,
  },
  emptyCard: {
    backgroundColor: Colors.card,
    borderRadius: 20,
    padding: 32,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderStyle: 'dashed',
  },
  emptyEmoji: {fontSize: 44, marginBottom: 14},
  emptyTitle: {
    fontSize: FontSize.base,
    fontWeight: FontWeight.bold,
    color: Colors.text.secondary,
    marginBottom: 6,
  },
  emptySubtitle: {
    fontSize: FontSize.sm,
    color: Colors.text.muted,
    textAlign: 'center',
    lineHeight: 18,
  },

  // ── Quick Actions ─────────────────────────────────────
  quickSection: {paddingHorizontal: 16, marginTop: 20, paddingBottom: 110},
  quickGrid: {flexDirection: 'row', flexWrap: 'wrap', gap: 12},
  quickCard: {
    width: '47%',
    backgroundColor: Colors.card,
    borderRadius: 18,
    padding: 18,
    shadowColor: Colors.shadow,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 3,
    gap: 10,
  },
  quickIconBg: {
    width: 46,
    height: 46,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickEmoji: {fontSize: 24},
  quickLabel: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.bold,
    color: Colors.text.primary,
    lineHeight: 18,
  },
  quickArrow: {
    fontSize: FontSize.sm,
    color: Colors.text.muted,
    marginTop: 2,
  },
});
