export const HOME_STRINGS = {
  GREETING_MORNING: 'Good Morning',
  GREETING_AFTERNOON: 'Good afternoon',
  GREETING_EVENING: 'Good Evening',
  GO_ONLINE: 'Go Online',
  GO_OFFLINE: 'Go Offline',
  ONLINE_DESC: "You're visible to customers",
  OFFLINE_DESC: "You're not receiving orders",
  TODAY_STATS: "Today's Summary",
  DELIVERIES: 'Deliveries',
  PLASTIC_KG: 'Plastic Collected',
  EARNINGS: "Today's Earnings",
  ACTIVE_ORDER: 'Active Order',
  NO_ACTIVE_ORDER: 'No active orders',
  GO_ONLINE_TO_RECEIVE: 'Go online to start receiving orders',
  VIEW_ORDER: 'View Order',
  QUICK_ACTIONS: 'Quick Actions',
  LOG_PLASTIC: 'Log Plastic',
  MY_EARNINGS: 'My Earnings',
  LEADERBOARD: 'Leaderboard',
  TRIP_HISTORY: 'Trip History',
};
