import {StyleSheet} from 'react-native';
import {Colors} from '../../constants/colors';
import {FontSize, FontWeight} from '../../constants/fonts';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: Colors.background},
  scroll: {flex: 1},

  // ── Offline state ─────────────────────────────────────────────
  offlineContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 40,
    paddingBottom: 40,
  },
  offlineIconBg: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#F1F5F9',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 28,
  },
  offlineTitle: {
    fontSize: FontSize.xxl,
    fontWeight: FontWeight.extraBold,
    color: Colors.text.primary,
    textAlign: 'center',
    marginBottom: 12,
  },
  offlineSubtitle: {
    fontSize: FontSize.base,
    color: Colors.text.secondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 36,
  },
  goOnlineBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.primary,
    paddingHorizontal: 40,
    paddingVertical: 18,
    borderRadius: 18,
    gap: 10,
    shadowColor: Colors.primary,
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 10,
  },
  goOnlineBtnText: {
    color: Colors.text.inverse,
    fontSize: FontSize.lg,
    fontWeight: FontWeight.extraBold,
    letterSpacing: 0.3,
  },

  // ── Online waiting state ──────────────────────────────────────
  waitingContainer: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 40,
  },
  pulseWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 120,
    height: 120,
    marginBottom: 32,
  },
  pulseRing: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: Colors.primary,
  },
  onlineIconBg: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: Colors.primary + '20',
    alignItems: 'center',
    justifyContent: 'center',
  },
  onlineTitle: {
    fontSize: FontSize.xxl,
    fontWeight: FontWeight.extraBold,
    color: Colors.text.primary,
    textAlign: 'center',
    marginBottom: 10,
  },
  onlineSubtitle: {
    fontSize: FontSize.base,
    color: Colors.text.secondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 36,
  },
  goOfflineBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: Colors.border,
    backgroundColor: Colors.card,
    paddingHorizontal: 28,
    paddingVertical: 14,
    borderRadius: 14,
    gap: 8,
  },
  goOfflineBtnText: {
    color: Colors.text.secondary,
    fontSize: FontSize.base,
    fontWeight: FontWeight.semiBold,
  },

  // ── Pending plastic card ──────────────────────────────────────
  plasticPendingCard: {
    alignSelf: 'stretch',
    backgroundColor: Colors.card,
    borderRadius: 18,
    padding: 16,
    marginTop: 28,
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: '#34D39930',
    shadowColor: '#34D399',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 4,
  },
  plasticPendingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
  },
  plasticPendingIconBg: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: '#34D39918',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  plasticPendingTitle: {
    fontSize: FontSize.base,
    fontWeight: FontWeight.bold,
    color: Colors.text.primary,
    flex: 1,
  },
  plasticPendingBadge: {
    backgroundColor: '#F59E0B',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    flexShrink: 0,
  },
  plasticPendingBadgeText: {
    fontSize: 11,
    fontWeight: FontWeight.bold,
    color: '#fff',
  },
  plasticStatsRow: {
    flexDirection: 'row',
    backgroundColor: '#F0FDF8',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 8,
    marginBottom: 14,
    justifyContent: 'space-around',
  },
  plasticStatItem: {
    alignItems: 'center',
    flex: 1,
  },
  plasticStatValue: {
    fontSize: FontSize.xl,
    fontWeight: FontWeight.extraBold,
    color: Colors.text.primary,
    marginBottom: 3,
  },
  plasticStatLabel: {
    fontSize: 11,
    color: Colors.text.muted,
    textAlign: 'center',
  },
  plasticStatDivider: {
    width: 1,
    marginVertical: 4,
    backgroundColor: '#D1FAE5',
  },
  submitPlasticBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#34D399',
    borderRadius: 14,
    paddingVertical: 15,
    gap: 8,
    shadowColor: '#34D399',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  submitPlasticBtnText: {
    color: '#fff',
    fontSize: FontSize.base,
    fontWeight: FontWeight.bold,
    letterSpacing: 0.3,
  },

});
