import {StyleSheet} from 'react-native';
import {Colors} from '../../constants/colors';
import {FontSize, FontWeight} from '../../constants/fonts';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: Colors.background},

  // Map area
  mapContainer: {
    height: 240,
    backgroundColor: '#DCFCE7',
    position: 'relative',
    overflow: 'hidden',
  },
  staticMapImage: {
    width: '100%',
    height: '100%',
  },
  mapFallback: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  mapBg: {fontSize: 72, opacity: 0.5},
  mapFallbackText: {
    fontSize: FontSize.sm,
    color: Colors.text.secondary,
  },
  // Route card (shown when map image fails to load)
  routeCard: {
    flex: 1,
    backgroundColor: '#F0FDF4',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  routeRow: {flexDirection: 'row', alignItems: 'stretch', gap: 14},
  routeDots: {alignItems: 'center', paddingTop: 4},
  routeDotGreen: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: Colors.accent,
    borderWidth: 2,
    borderColor: Colors.card,
  },
  routeLine: {
    width: 2,
    flex: 1,
    backgroundColor: Colors.accent + '50',
    marginVertical: 4,
    minHeight: 36,
  },
  routeDotRed: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#EF4444',
    borderWidth: 2,
    borderColor: Colors.card,
  },
  routeLabels: {flex: 1, justifyContent: 'space-between', gap: 6},
  routeStop: {gap: 1},
  routeStopLabel: {
    fontSize: 9,
    fontWeight: FontWeight.bold,
    color: Colors.text.muted,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  routeStopName: {
    fontSize: FontSize.base,
    fontWeight: FontWeight.bold,
    color: Colors.text.primary,
  },
  routeStopAddr: {
    fontSize: FontSize.xs,
    color: Colors.text.secondary,
  },
  routeDistancePill: {
    alignSelf: 'flex-start',
    backgroundColor: Colors.primary + '12',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  routeDistanceText: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.semiBold,
    color: Colors.primary,
  },
  // Destination chip (top-left overlay on map)
  destinationChip: {
    position: 'absolute',
    top: 14,
    left: 14,
    backgroundColor: Colors.card,
    borderRadius: 20,
    paddingVertical: 7,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 5,
  },
  destinationChipText: {
    fontSize: FontSize.xs,
    fontWeight: FontWeight.bold,
    color: Colors.text.primary,
    maxWidth: 180,
  },
  // Navigate button (bottom-right overlay on map)
  navigateBtn: {
    position: 'absolute',
    bottom: 14,
    right: 14,
    backgroundColor: Colors.primary,
    borderRadius: 22,
    paddingVertical: 10,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    shadowColor: Colors.shadow,
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },
  navigateBtnIcon: {fontSize: 16},
  navigateBtnText: {
    color: Colors.text.inverse,
    fontWeight: FontWeight.bold,
    fontSize: FontSize.sm,
    letterSpacing: 0.3,
  },

  // Status steps
  statusBar: {
    backgroundColor: Colors.card,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  statusDotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  statusConnector: {
    flex: 1,
    height: 2,
    borderRadius: 1,
  },
  statusLabelsRow: {
    flexDirection: 'row',
  },
  statusStep: {flex: 1, alignItems: 'center'},
  statusStepDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  statusStepLabel: {
    flex: 1,
    fontSize: 9,
    color: Colors.text.muted,
    textAlign: 'center',
  },
  statusStepActive: {color: Colors.primary, fontWeight: FontWeight.bold},

  scroll: {flex: 1},

  // Tab switcher
  tabBar: {
    flexDirection: 'row',
    backgroundColor: Colors.card,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 0,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    paddingBottom: 10,
    marginHorizontal: 4,
  },
  tabActive: {
    borderBottomWidth: 2,
    borderBottomColor: Colors.primary,
  },
  tabText: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semiBold,
    color: Colors.text.secondary,
  },
  tabTextActive: {
    color: Colors.primary,
    fontWeight: FontWeight.bold,
  },
  tabBadge: {
    backgroundColor: Colors.primary,
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    marginLeft: 6,
  },
  tabBadgeText: {
    fontSize: 10,
    fontWeight: FontWeight.bold,
    color: Colors.text.inverse,
  },
  tabRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },

  // Detail cards
  detailSection: {padding: 16},
  sectionCard: {
    backgroundColor: Colors.card,
    borderRadius: 20,
    padding: 18,
    marginBottom: 14,
    shadowColor: Colors.shadow,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
  },
  sectionHeader: {flexDirection: 'row', alignItems: 'center', marginBottom: 14, gap: 8},
  sectionEmoji: {fontSize: 18},
  sectionTitle: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.bold,
    color: Colors.text.primary,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  infoRow: {flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8},
  infoLabel: {fontSize: FontSize.sm, color: Colors.text.secondary},
  infoValue: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semiBold,
    color: Colors.text.primary,
    maxWidth: '60%',
    textAlign: 'right',
  },
  divider: {height: 1, backgroundColor: Colors.borderLight, marginVertical: 10},
  itemRow: {flexDirection: 'row', alignItems: 'center', paddingVertical: 7},
  itemDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.accent,
    marginRight: 10,
  },
  itemName: {flex: 1, fontSize: FontSize.sm, color: Colors.text.primary},
  itemQty: {fontSize: FontSize.xs, color: Colors.text.secondary},
  itemPrice: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.bold,
    color: Colors.primary,
    marginLeft: 8,
  },

  // Actions
  actionSection: {
    padding: 16,
    paddingBottom: 110,
    gap: 10,
  },
  primaryAction: {
    backgroundColor: Colors.primary,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    shadowColor: Colors.shadow,
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  primaryActionText: {
    color: Colors.text.inverse,
    fontWeight: FontWeight.bold,
    fontSize: FontSize.md,
    letterSpacing: 0.3,
  },
  plasticAction: {
    backgroundColor: Colors.accent + '18',
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: Colors.accent,
  },
  plasticActionText: {
    color: Colors.accent,
    fontWeight: FontWeight.bold,
    fontSize: FontSize.base,
  },
  callRow: {flexDirection: 'row', gap: 10},
  callBtn: {
    flex: 1,
    backgroundColor: Colors.card,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
    gap: 4,
  },
  callBtnText: {
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semiBold,
    color: Colors.text.primary,
  },

  // Plastic collection card
  plasticCard: {
    backgroundColor: Colors.card,
    borderRadius: 18,
    padding: 18,
    borderWidth: 1.5,
    borderColor: Colors.accent,
    gap: 14,
  },
  plasticCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  plasticCardHeaderText: {flex: 1},
  plasticCardTitle: {
    fontSize: FontSize.base,
    fontWeight: FontWeight.extraBold,
    color: Colors.text.primary,
  },
  plasticCardSubtitle: {
    fontSize: FontSize.xs,
    color: Colors.text.secondary,
    marginTop: 2,
  },
  weightRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.background,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 10,
  },
  weightInput: {
    flex: 1,
    fontSize: FontSize.xxl,
    fontWeight: FontWeight.extraBold,
    color: Colors.text.primary,
    padding: 0,
  },
  weightUnit: {
    fontSize: FontSize.lg,
    color: Colors.text.muted,
    fontWeight: FontWeight.semiBold,
  },
  noPlasticRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  noPlasticCheckbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: Colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noPlasticCheckboxActive: {
    backgroundColor: Colors.accent,
    borderColor: Colors.accent,
  },
  noPlasticLabel: {
    fontSize: FontSize.sm,
    color: Colors.text.secondary,
  },
  incentiveRow: {
    flexDirection: 'row',
    backgroundColor: Colors.primary + '0A',
    borderRadius: 12,
    padding: 12,
  },
  incentiveItem: {
    flex: 1,
    alignItems: 'center',
    gap: 2,
  },
  incentiveDivider: {
    width: 1,
    backgroundColor: Colors.borderLight,
    marginVertical: 4,
  },
  incentiveValue: {
    fontSize: FontSize.lg,
    fontWeight: FontWeight.extraBold,
    color: Colors.primary,
  },
  incentiveLabel: {
    fontSize: FontSize.xs,
    color: Colors.text.muted,
    textAlign: 'center',
  },
  collectBtn: {
    backgroundColor: Colors.accent,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    shadowColor: Colors.accent,
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  collectBtnDisabled: {
    opacity: 0.4,
    shadowOpacity: 0,
    elevation: 0,
  },
  collectBtnText: {
    color: Colors.text.inverse,
    fontWeight: FontWeight.bold,
    fontSize: FontSize.md,
    letterSpacing: 0.3,
  },

  // Empty
  emptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  emptyEmoji: {fontSize: 72, marginBottom: 24, opacity: 0.8},
  emptyTitle: {
    fontSize: FontSize.xl,
    fontWeight: FontWeight.bold,
    color: Colors.text.primary,
    marginBottom: 10,
  },
  emptySubtitle: {
    fontSize: FontSize.base,
    color: Colors.text.secondary,
    textAlign: 'center',
    lineHeight: 22,
  },
});
