export const PROFILE_STRINGS = {
  TITLE: 'My Profile',
  VEHICLE: 'Vehicle Details',
  STATS: 'My Stats',
  SETTINGS: 'Settings',
  LOGOUT: 'Logout',
  TOTAL_DELIVERIES: 'Total Deliveries',
  RATING: 'Rating',
  TOTAL_PLASTIC: 'Total Plastic (kg)',
  JOINED: 'Joined',
  VEHICLE_TYPE: 'Vehicle Type',
  VEHICLE_NUMBER: 'Vehicle Number',
  CITY: 'City',
  NOTIFICATIONS: 'Notifications',
  LANGUAGE: 'Language',
  HELP: 'Help & Support',
  PRIVACY: 'Privacy Policy',
  VERSION: 'App Version',
  LOGOUT_CONFIRM: 'Are you sure you want to logout?',
  LOGOUT_CANCEL: 'Cancel',
  LOGOUT_CONFIRM_BTN: 'Logout',
};
