import {StyleSheet} from 'react-native';
import {Colors} from '../../constants/colors';
import {FontSize, FontWeight} from '../../constants/fonts';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: Colors.background},
  topBg: {
    backgroundColor: Colors.primary,
    paddingTop: 60,
    paddingBottom: 44,
    paddingHorizontal: 28,
    borderBottomLeftRadius: 36,
    borderBottomRightRadius: 36,
  },
  backBtn: {marginBottom: 24, alignSelf: 'flex-start'},
  backText: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: FontSize.xl,
    fontWeight: FontWeight.bold,
  },
  title: {
    fontSize: FontSize.xxl,
    fontWeight: FontWeight.extraBold,
    color: Colors.text.inverse,
    marginBottom: 10,
  },
  subtitle: {fontSize: FontSize.base, color: Colors.text.light, lineHeight: 22},
  phone: {color: Colors.cta, fontWeight: FontWeight.bold},
  body: {paddingHorizontal: 28, paddingTop: 8},
  otpRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 36,
    marginBottom: 8,
    gap: 10,
  },
  otpBox: {
    flex: 1,
    height: 72,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: Colors.border,
    backgroundColor: Colors.card,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.shadow,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  otpBoxFocused: {
    borderColor: Colors.primary,
    backgroundColor: '#F0FDF4',
    shadowOpacity: 0.1,
  },
  otpBoxFilled: {
    borderColor: Colors.accent,
    backgroundColor: Colors.ctaLight,
  },
  otpDigit: {
    fontSize: FontSize.xxl,
    fontWeight: FontWeight.extraBold,
    color: Colors.text.primary,
    textAlign: 'center',
    width: '100%',
    height: '100%',
    padding: 0,
  },
  errorText: {
    color: Colors.error,
    fontSize: FontSize.xs,
    textAlign: 'center',
    marginTop: 10,
    fontWeight: FontWeight.medium,
  },
  verifyBtn: {marginTop: 32},
  resendRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 24,
    flexWrap: 'wrap',
    gap: 4,
  },
  resendText: {fontSize: FontSize.sm, color: Colors.text.secondary},
  resendLink: {
    fontSize: FontSize.sm,
    color: Colors.primary,
    fontWeight: FontWeight.bold,
  },
  resendDisabled: {color: Colors.text.muted},
  changeNumber: {
    textAlign: 'center',
    marginTop: 18,
    color: Colors.primary,
    fontSize: FontSize.sm,
    fontWeight: FontWeight.semiBold,
  },
  demoHint: {
    textAlign: 'center',
    marginTop: 28,
    color: Colors.text.muted,
    fontSize: FontSize.xs,
    fontStyle: 'italic',
  },
  hiddenInput: {
    position: 'absolute',
    width: 1,
    height: 1,
    opacity: 0,
  },
});
